# Generated by Django 5.1.4 on 2025-01-09 11:20

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_remove_groupprofile_creator_user_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuddyProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('about', models.TextField(blank=True, null=True)),
                ('fitness_goals', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Weight Loss', 'Weight Loss'), ('Muscle Gain', 'Muscle Gain'), ('General Fitness', 'General Fitness'), ('Cardio', 'Cardio'), ('Flexibility', 'Flexibility')], max_length=58)),
                ('workout_preferences', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('gym', 'Gym'), ('yoga', 'Yoga'), ('running', 'Running'), ('cycling', 'Cycling'), ('swimming', 'Swimming')], max_length=33)),
                ('availability', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('weekends', 'Weekends')], max_length=34)),
                ('milestones', models.TextField(blank=True, help_text='Add key fitness milestones or achievements')),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_visibility', models.BooleanField(default=True, help_text='Allow showing email on profile')),
            ],
        ),
    ]
