# Generated by Django 5.1.4 on 2025-01-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_portal', '0002_remove_buddyprofile_email_visibility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddyprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default.png', null=True, upload_to='profile_pics/'),
        ),
    ]
