# Generated by Django 5.1.4 on 2025-01-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_portal', '0004_alter_buddyprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='buddyprofile',
            name='show_id_in_buddy_portal',
            field=models.BooleanField(default=True),
        ),
    ]
