# Generated by Django 5.1.4 on 2025-01-13 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_portal', '0005_buddyprofile_show_id_in_buddy_portal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buddyprofile',
            name='show_id_in_buddy_portal',
        ),
    ]
