# Generated by Django 5.1.4 on 2025-01-15 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_portal', '0007_buddyprofile_show_in_buddy_finder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buddyprofile',
            name='show_in_buddy_finder',
        ),
    ]
