# Generated by Django 5.1.4 on 2025-01-13 11:11

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='activity_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('gym', 'Gym'), ('yoga', 'Yoga'), ('running', 'Running'), ('cycling', 'Cycling'), ('swimming', 'Swimming'), ('dance', 'Dance'), ('aerobics', 'Aerobics')], max_length=48),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='location',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('park', 'Park'), ('gym', 'Gym'), ('community center', 'Community Center'), ('beach', 'Beach'), ('indoor', 'Indoor Facility'), ('outdoor', 'Outdoor Location')], max_length=46),
        ),
        migrations.AlterField(
            model_name='group',
            name='schedule',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('weekends', 'Weekends'), ('weekday nights', 'Weekday Nights')], max_length=49),
        ),
    ]
