# Generated by Django 5.1.4 on 2025-01-15 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_portal', '0003_grouporganiserprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouporganiserprofile',
            old_name='profile_picture',
            new_name='group_picture',
        ),
    ]
