# Generated by Django 5.1.4 on 2025-01-15 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_portal', '0004_rename_profile_picture_grouporganiserprofile_group_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='profile_picture',
            new_name='group_picture',
        ),
        migrations.RenameField(
            model_name='grouporganiserprofile',
            old_name='group_picture',
            new_name='group_organiser_picture',
        ),
    ]
