# Generated by Django 5.1.4 on 2025-01-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_portal', '0005_rename_profile_picture_group_group_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(default='Default Group Name', max_length=100, unique=True),
        ),
    ]
