# Generated by Django 5.1.4 on 2025-01-16 19:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_portal', '0007_grouporganiserprofile_show_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='group_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
