# Generated by Django 5.1.4 on 2025-01-17 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_portal', '0009_groupmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupMessage',
        ),
    ]
